apiVersion: v1
kind: Service
metadata:
  labels:
    app: crossbar-estimator
  name: crossbar-estimator
  namespace: dev
spec:
  ports:
    - port: 8080
      name: main
      protocol: TCP
      targetPort: 8080
  selector:
    app: crossbar-estimator
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crossbar-estimator
  namespace: dev
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: crossbar-estimator
      annotations:
        wikia.com/keys: '{"es_logs": {"container_name": "crossbar-estimator", "es_index": "crossbar-estimator" }}'
    spec:
      containers:
        - name: crossbar-estimator
          image: crossbario/crossbar
          readinessProbe:
            httpGet:
              path: /info
              port: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 20
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: crossbar-estimator
  namespace: dev
spec:
  rules:
    - host: crossbar-estimator.fandom-dev.us
      http:
        paths:
          - backend:
              serviceName: crossbar-estimator
              servicePort: 8080
